CREATE TABLE `c_all` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `LastName` varchar(500) DEFAULT NULL,
  `FirstName` varchar(500) DEFAULT NULL,
  `AgencyCompany` varchar(500) DEFAULT NULL,
  `JobTitle` varchar(500) DEFAULT NULL,
  `DOB` varchar(500) DEFAULT NULL,
  `POB` varchar(500) DEFAULT NULL,
  `SSN` varchar(500) DEFAULT NULL,
  `ClearanceLevel` varchar(500) DEFAULT NULL,
  `ClearanceGranted` varchar(500) DEFAULT NULL,
  `GrantingAgency` varchar(500) DEFAULT NULL,
  `InvestigationType` varchar(500) DEFAULT NULL,
  `InvestigatingAgency` varchar(500) DEFAULT NULL,
  `InvestigationDate` varchar(500) DEFAULT NULL,
  `Database1` varchar(500) DEFAULT NULL,
  `VerifiedBy` varchar(500) DEFAULT NULL,
  `CertAuthority` varchar(500) DEFAULT NULL,
  `Status` varchar(500) DEFAULT NULL,
  `Submitted` varchar(500) DEFAULT NULL,
  `comments` varchar(500) DEFAULT NULL,
  `VARStartDate` varchar(500) DEFAULT NULL,
  `VAREndDate` varchar(500) DEFAULT NULL,
  `ContractNumber` varchar(500) DEFAULT NULL,
  `DutyLocation` varchar(500) DEFAULT NULL,
  `RequestDate` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM COMMENT='Table with requestdate column.';
