insert into serials (software, license, ownername) values ('.NET Micro Framework Porting Kit v3.0','C64GF-QGX43-2PMM3-KFGKM-Q66PR','Paul Johnson');
insert into serials (software, license, ownername) values ('Virtual PC for Mac 7.0','KPKV3-V9R8X-QMTGH-YXTCG-8P6HM','Paul Johnson');
insert into serials (software, license, ownername) values ('Visual Studio Team Explorer Everywhere 2010','7W3RJ-4WX3R-BV8JM-FC8P7-3W7QX','Paul Johnson');
insert into serials (software, license, ownername) values ('Visual Studio Express 2012 for Web','BWVK8-FD442-K2GCM-98B84-J8WRV','Paul Johnson');
insert into serials (software, license, ownername) values ('Visual Studio Express 2012 for Windows 8','YCX46-9PQR6-YKMC9-2B8KQ-6CDHX','Paul Johnson');
insert into serials (software, license, ownername) values ('Visual Studio Express 2012 for Windows Desktop','YDF6K-W7M6M-WT2G4-R474C-Y8CQF','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows 7 Ultimate and Ultimate K','2PR9M-9DRM9-994WG-VQMMT-42TYB','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows 7 Ultimate and Ultimate K','MPTJ8-RWTD3-M8P6B-R2FDQ-FY6X9','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows 7 Ultimate and Ultimate K','6QR4Y-C97BP-X6Q2F-GXKVD-DJK98','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows 7 Ultimate and Ultimate K','FCQGH-9CJBR-3GK7B-WGYB4-9B4VH','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows 7 Ultimate and Ultimate K','PYPRF-C32J3-YXFW7-KJRPR-QQD24','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows 7 Ultimate and Ultimate K','P6K6M-VTJRK-J6R78-994QD-TW6TM','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows 7 Ultimate and Ultimate K','TPV2X-CKTRB-DY89B-XKG4G-7WQDH','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows 7 Enterprise, N, K, and KN','W6W9D-XTVCY-HCDCM-PCGTY-FYG6K','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows Advanced Server, Limited Edition','F3VWH-8KTY3-WR2WF-4GQQH-VCXTB','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows Server 2003 R2 Enterprise Edition','KB9W7-M99H4-BMJB8-9FXCJ-M3JK8','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows Server 2003 R2 Enterprise Edition','VKGC9-WM4DP-8XKQJ-PJVR6-6RKHJ','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows Server 2008 R2 Standard and Enterprise','CYF4T-R3C3C-MGJM4-F2JQM-V8RJM','Paul Johnson');
insert into serials (software, license, ownername) values ('Services for Unix 2.0','TCJC7-H2QDH-3T7G7-R6RTM-YRK3Y','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows XP Professional','RH4MY-6DPK6-K7WYR-GGD46-CQ896','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows XP Professional','CPF8C-3Q3YH-3VC9J-JPJBX-XB4R8','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows XP Professional Edition K','WRQBQ-MH49W-TG23H-99H38-H2JY8','Paul Johnson');
insert into serials (software, license, ownername) values ('Windows XP Professional Edition K','V32XM-YJR9K-VQCHX-R3TWK-MFBRY','Paul Johnson');
