update us_states set electoral_votes = 9 where state = "Alabama";
update us_states set electoral_votes = 3 where state = "Alaska";
update us_states set electoral_votes = 11 where state = "Arizona";
update us_states set electoral_votes = 6 where state = "Arkansas";
update us_states set electoral_votes = 55 where state = "California";
update us_states set electoral_votes = 9 where state = "Colorado";
update us_states set electoral_votes = 7 where state = "Connecticut";
update us_states set electoral_votes = 3 where state = "Delaware";
update us_states set electoral_votes = 29 where state = "Florida";
update us_states set electoral_votes = 16 where state = "Georgia";
update us_states set electoral_votes = 4 where state = "Hawaii";
update us_states set electoral_votes = 4 where state = "Idaho";
update us_states set electoral_votes = 20 where state = "Illinois";
update us_states set electoral_votes = 11 where state = "Indiana";
update us_states set electoral_votes = 6 where state = "Iowa";
update us_states set electoral_votes = 6 where state = "Kansas";
update us_states set electoral_votes = 8 where state = "Kentucky";
update us_states set electoral_votes = 8 where state = "Louisiana";
update us_states set electoral_votes = 4 where state = "Maine";
update us_states set electoral_votes = 10 where state = "Maryland";
update us_states set electoral_votes = 11 where state = "Massachusetts";
update us_states set electoral_votes = 16 where state = "Michigan";
update us_states set electoral_votes = 10 where state = "Minnesota";
update us_states set electoral_votes = 6 where state = "Mississippi";
update us_states set electoral_votes = 10 where state = "Missouri";
update us_states set electoral_votes = 3 where state = "Montana";
update us_states set electoral_votes = 5 where state = "Nebraska";
update us_states set electoral_votes = 6 where state = "Nevada";
update us_states set electoral_votes = 4 where state = "New Hampshire";
update us_states set electoral_votes = 14 where state = "New Jersey";
update us_states set electoral_votes = 5 where state = "New Mexico";
update us_states set electoral_votes = 29 where state = "New York";
update us_states set electoral_votes = 15 where state = "North Carolina";
update us_states set electoral_votes = 3 where state = "North Dakota";
update us_states set electoral_votes = 18 where state = "Ohio";
update us_states set electoral_votes = 7 where state = "Oklahoma";
update us_states set electoral_votes = 7 where state = "Oregon";
update us_states set electoral_votes = 20 where state = "Pennsylvania";
update us_states set electoral_votes = 4 where state = "Rhode Island";
update us_states set electoral_votes = 9 where state = "South Carolina";
update us_states set electoral_votes = 3 where state = "South Dakota";
update us_states set electoral_votes = 11 where state = "Tennessee";
update us_states set electoral_votes = 38 where state = "Texas";
update us_states set electoral_votes = 6 where state = "Utah";
update us_states set electoral_votes = 3 where state = "Vermont";
update us_states set electoral_votes = 13 where state = "Virginia";
update us_states set electoral_votes = 12 where state = "Washington";
update us_states set electoral_votes = 5 where state = "West Virginia";
update us_states set electoral_votes = 10 where state = "Wisconsin";
update us_states set electoral_votes = 3 where state = "Wyoming";
